import { PlatformRole, TenantRole } from "@prisma/client";

export const TENANT_PERMISSIONS = [
  "DASHBOARD_VIEW",
  "CUSTOMERS_VIEW", "CUSTOMERS_CREATE", "CUSTOMERS_EDIT", "CUSTOMERS_DEACTIVATE",
  "CUSTOMER_BRANCH_CREATE", "CUSTOMER_BRANCH_EDIT", "CUSTOMER_BRANCH_DEACTIVATE",
  "CUSTOMER_CONTACT_CREATE", "CUSTOMER_CONTACT_EDIT", "CUSTOMER_CONTACT_DEACTIVATE",
  "CUSTOMER_ADDRESS_CREATE", "CUSTOMER_ADDRESS_EDIT", "CUSTOMER_ADDRESS_DEACTIVATE",
  "SUPPLIERS_VIEW", "SUPPLIERS_CREATE", "SUPPLIERS_EDIT", "SUPPLIERS_DEACTIVATE",
  "SUPPLIER_CONTACT_CREATE", "SUPPLIER_CONTACT_EDIT", "SUPPLIER_CONTACT_DEACTIVATE",
  "SUPPLIER_ADDRESS_CREATE", "SUPPLIER_ADDRESS_EDIT", "SUPPLIER_ADDRESS_DEACTIVATE",
  "SUPPLIER_BRANDS_MANAGE",
  "PARTS_VIEW", "PARTS_CREATE", "PARTS_EDIT", "PARTS_DEACTIVATE",
  "MANUFACTURERS_VIEW", "MANUFACTURERS_CREATE", "MANUFACTURERS_EDIT", "MANUFACTURERS_DEACTIVATE",
  "STORAGE_LOCATIONS_VIEW", "STORAGE_LOCATIONS_CREATE", "STORAGE_LOCATIONS_EDIT", "STORAGE_LOCATIONS_DEACTIVATE",
  "SERVICES_VIEW", "SERVICES_CREATE", "SERVICES_EDIT", "SERVICES_DEACTIVATE",
  "TAX_CODES_VIEW", "TAX_CODES_CREATE", "TAX_CODES_EDIT",
  "COMMERCIAL_TERMS_VIEW", "COMMERCIAL_TERMS_CREATE", "COMMERCIAL_TERMS_EDIT",
  "NUMBERING_VIEW", "NUMBERING_EDIT", "COMPANY_SETTINGS_VIEW", "COMPANY_SETTINGS_EDIT",
  "JOBS_VIEW", "JOBS_CREATE", "JOBS_EDIT", "JOBS_DELETE",
  "INVENTORY_VIEW", "INVENTORY_RECEIVE", "INVENTORY_ISSUE", "INVENTORY_TRANSFER", "INVENTORY_ADJUST",
  "PEX_VIEW", "PEX_CREATE", "PEX_EDIT", "PEX_RELINK", "PEX_SCRAP",
  "QUOTES_VIEW", "QUOTES_CREATE", "QUOTES_EDIT_DRAFT", "QUOTES_VIEW_COST", "QUOTES_VIEW_MARGIN",
  "QUOTES_EDIT_COST", "QUOTES_EDIT_PRICE", "QUOTES_APPLY_DISCOUNT", "QUOTES_APPROVE",
  "QUOTES_SEND", "QUOTES_ACCEPT_DECLINE", "QUOTES_REVISE", "QUOTES_CANCEL",
  "QUOTES_CONVERT_TO_SALES_ORDER", "QUOTES_EXPORT",
  "SALES_ORDERS_VIEW", "SALES_ORDERS_CREATE_DIRECT", "SALES_ORDERS_CREATE_FROM_QUOTE",
  "SALES_ORDERS_EDIT_DRAFT", "SALES_ORDERS_CONFIRM", "SALES_ORDERS_LINK_JOBS",
  "SALES_ORDERS_LINK_PEX", "SALES_ORDERS_FULFIL", "SALES_ORDERS_REVERSE_FULFILMENT",
  "SALES_ORDERS_CANCEL", "SALES_ORDERS_VIEW_COST", "SALES_ORDERS_CREATE_INVOICE",
  "INVOICES_VIEW", "INVOICES_CREATE", "INVOICES_CREATE_FROM_JOB", "INVOICES_CREATE_FROM_SALES_ORDER",
  "INVOICES_EDIT_DRAFT", "INVOICES_VIEW_COST_MARGIN", "INVOICES_APPROVE", "INVOICES_ISSUE",
  "INVOICES_CANCEL", "INVOICES_RECORD_PAYMENT", "INVOICES_EXPORT",
  "FINANCIAL_REPORTS_VIEW", "FINANCIAL_REPORTS_EXPORT",
  "REPORTS_VIEW", "REPORTS_EXPORT", "USERS_MANAGE", "SETTINGS_MANAGE", "AUDIT_VIEW",
] as const;

export type TenantPermission = (typeof TENANT_PERMISSIONS)[number];

export const PLATFORM_PERMISSIONS = [
  "PLATFORM_COMPANIES_VIEW",
  "PLATFORM_COMPANIES_CREATE",
  "PLATFORM_COMPANIES_EDIT",
  "PLATFORM_COMPANIES_SUSPEND",
  "PLATFORM_ENTITLEMENTS_MANAGE",
  "PLATFORM_TENANT_ADMINS_MANAGE",
  "PLATFORM_CONFIGURATION_MANAGE",
  "PLATFORM_AUDIT_VIEW",
  "PLATFORM_SUPPORT_READ",
  "PLATFORM_SUPPORT_WRITE",
  "PLATFORM_OPERATORS_MANAGE",
] as const;

export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[number];

const ALL_TENANT = new Set<TenantPermission>(TENANT_PERMISSIONS);
export const SUPPORT_READ_TENANT_PERMISSIONS = new Set<TenantPermission>(
  TENANT_PERMISSIONS.filter((permission) => permission.endsWith("_VIEW") || permission.endsWith("_EXPORT") || permission === "DASHBOARD_VIEW" || permission === "AUDIT_VIEW"),
);
export const SUPPORT_WRITE_TENANT_PERMISSIONS = ALL_TENANT;
const MANAGER = new Set<TenantPermission>([
  "DASHBOARD_VIEW", "CUSTOMERS_VIEW", "CUSTOMERS_CREATE", "CUSTOMERS_EDIT",
  "CUSTOMER_BRANCH_CREATE", "CUSTOMER_BRANCH_EDIT", "CUSTOMER_BRANCH_DEACTIVATE", "CUSTOMER_CONTACT_CREATE", "CUSTOMER_CONTACT_EDIT", "CUSTOMER_CONTACT_DEACTIVATE", "CUSTOMER_ADDRESS_CREATE", "CUSTOMER_ADDRESS_EDIT", "CUSTOMER_ADDRESS_DEACTIVATE",
  "SUPPLIERS_VIEW", "SUPPLIERS_CREATE", "SUPPLIERS_EDIT",
  "SUPPLIER_CONTACT_CREATE", "SUPPLIER_CONTACT_EDIT", "SUPPLIER_CONTACT_DEACTIVATE", "SUPPLIER_ADDRESS_CREATE", "SUPPLIER_ADDRESS_EDIT", "SUPPLIER_ADDRESS_DEACTIVATE", "SUPPLIER_BRANDS_MANAGE",
  "JOBS_VIEW", "JOBS_CREATE", "JOBS_EDIT", "INVENTORY_VIEW", "INVENTORY_ISSUE",
  "PEX_VIEW", "PEX_CREATE", "PEX_EDIT", "QUOTES_VIEW", "QUOTES_CREATE", "QUOTES_EDIT_DRAFT",
  "QUOTES_EDIT_PRICE", "QUOTES_SEND", "SALES_ORDERS_VIEW", "SALES_ORDERS_CREATE_FROM_QUOTE",
  "SALES_ORDERS_EDIT_DRAFT", "SALES_ORDERS_LINK_JOBS", "SALES_ORDERS_LINK_PEX",
  "REPORTS_VIEW", "REPORTS_EXPORT", "AUDIT_VIEW",
]);
const USER = new Set<TenantPermission>(["DASHBOARD_VIEW", "CUSTOMERS_VIEW", "JOBS_VIEW", "JOBS_EDIT", "INVENTORY_VIEW", "INVENTORY_ISSUE", "PEX_VIEW"]);
const STORES = new Set<TenantPermission>(["DASHBOARD_VIEW", "JOBS_VIEW", "INVENTORY_VIEW", "INVENTORY_RECEIVE", "INVENTORY_ISSUE", "INVENTORY_TRANSFER", "INVENTORY_ADJUST", "PEX_VIEW", "REPORTS_VIEW"]);
const SALES = new Set<TenantPermission>(["DASHBOARD_VIEW", "CUSTOMERS_VIEW", "CUSTOMERS_CREATE", "CUSTOMERS_EDIT", "CUSTOMER_BRANCH_CREATE", "CUSTOMER_BRANCH_EDIT", "CUSTOMER_CONTACT_CREATE", "CUSTOMER_CONTACT_EDIT", "CUSTOMER_ADDRESS_CREATE", "CUSTOMER_ADDRESS_EDIT", "SUPPLIERS_VIEW", "JOBS_VIEW", "QUOTES_VIEW", "QUOTES_CREATE", "QUOTES_EDIT_DRAFT", "QUOTES_EDIT_PRICE", "QUOTES_APPLY_DISCOUNT", "QUOTES_SEND", "QUOTES_REVISE", "QUOTES_EXPORT", "SALES_ORDERS_VIEW", "SALES_ORDERS_CREATE_FROM_QUOTE", "SALES_ORDERS_EDIT_DRAFT"]);
const FINANCE = new Set<TenantPermission>(["DASHBOARD_VIEW", "CUSTOMERS_VIEW", "JOBS_VIEW", "QUOTES_VIEW", "QUOTES_VIEW_COST", "QUOTES_VIEW_MARGIN", "SALES_ORDERS_VIEW", "SALES_ORDERS_VIEW_COST", "SALES_ORDERS_CREATE_INVOICE", "INVOICES_VIEW", "INVOICES_CREATE", "INVOICES_CREATE_FROM_JOB", "INVOICES_CREATE_FROM_SALES_ORDER", "INVOICES_EDIT_DRAFT", "INVOICES_VIEW_COST_MARGIN", "INVOICES_APPROVE", "INVOICES_ISSUE", "INVOICES_RECORD_PAYMENT", "INVOICES_EXPORT", "FINANCIAL_REPORTS_VIEW", "FINANCIAL_REPORTS_EXPORT", "REPORTS_VIEW"]);

export const DEFAULT_TENANT_PERMISSIONS: Record<TenantRole, ReadonlySet<TenantPermission>> = {
  COMPANY_ADMIN: ALL_TENANT,
  MANAGER,
  USER,
  STORE_CONTROLLER: STORES,
  SALES,
  FINANCE,
};

const ALL_PLATFORM = new Set<PlatformPermission>(PLATFORM_PERMISSIONS);
export const DEFAULT_PLATFORM_PERMISSIONS: Record<PlatformRole, ReadonlySet<PlatformPermission>> = {
  PLATFORM_ADMIN: ALL_PLATFORM,
  SUPPORT_READ_ONLY: new Set(["PLATFORM_COMPANIES_VIEW", "PLATFORM_SUPPORT_READ"]),
  SUPPORT_OPERATOR: new Set(["PLATFORM_COMPANIES_VIEW", "PLATFORM_SUPPORT_READ", "PLATFORM_SUPPORT_WRITE"]),
  SECURITY_AUDITOR: new Set(["PLATFORM_COMPANIES_VIEW", "PLATFORM_AUDIT_VIEW", "PLATFORM_SUPPORT_READ"]),
};

export function mergePermissionOverrides<T extends string>(defaults: ReadonlySet<T>, rows: ReadonlyArray<{ permission: string; allowed: boolean }>) {
  const effective = new Set(defaults);
  for (const row of rows) {
    if (row.allowed) effective.add(row.permission as T);
    else effective.delete(row.permission as T);
  }
  return effective;
}
