import { Prisma } from "@prisma/client";
import { z } from "zod";
import type { RequestContext } from "@/lib/auth/context-types";
import type { TenantPermission } from "@/lib/auth/permissions";
import { requireModule, requireTenantPermission } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

const optionalText = z.string().trim().max(500).optional().nullable();
// canReceiveRfq is only ever a real column on SupplierContact — parsed here
// for both parents (one shared schema, same pattern as branchId below) but
// dropped before writing a CustomerContact row; see the two "customer"
// branches in createChild/updateChild.
export const contactSchema = z.object({ firstName:z.string().trim().min(1).max(100),lastName:optionalText,position:optionalText,telephone:optionalText,mobile:optionalText,email:z.string().trim().email().optional().nullable().or(z.literal("")),notes:z.string().trim().max(3000).optional().nullable(),isPrimary:z.boolean().default(false),active:z.boolean().default(true),branchId:z.string().cuid().optional().nullable(),canReceiveRfq:z.boolean().default(false) });
export const addressSchema = z.object({ type:z.enum(["BILLING","DELIVERY","PHYSICAL","POSTAL"]),label:z.string().trim().max(100).optional().nullable(),line1:z.string().trim().min(1).max(200),line2:z.string().trim().max(200).optional().nullable(),city:z.string().trim().max(100).optional().nullable(),province:z.string().trim().max(100).optional().nullable(),postalCode:z.string().trim().max(20).optional().nullable(),countryCode:z.string().trim().length(2).default("ZA"),isPrimary:z.boolean().default(false),active:z.boolean().default(true),branchId:z.string().cuid().optional().nullable() });
export const branchSchema = z.object({ name:z.string().trim().min(1).max(150),code:z.string().trim().max(50).optional().nullable(),mainTelephone:optionalText,mainEmail:z.string().trim().email().optional().nullable().or(z.literal("")),notes:z.string().trim().max(3000).optional().nullable(),active:z.boolean().default(true) });
export type ParentKind="customer"|"supplier"; export type ChildKind="contacts"|"addresses"|"branches"; type Action="CREATE"|"EDIT"|"DEACTIVATE";
const permissions:Record<ParentKind,Partial<Record<ChildKind,Record<Action,TenantPermission>>>>={customer:{branches:{CREATE:"CUSTOMER_BRANCH_CREATE",EDIT:"CUSTOMER_BRANCH_EDIT",DEACTIVATE:"CUSTOMER_BRANCH_DEACTIVATE"},contacts:{CREATE:"CUSTOMER_CONTACT_CREATE",EDIT:"CUSTOMER_CONTACT_EDIT",DEACTIVATE:"CUSTOMER_CONTACT_DEACTIVATE"},addresses:{CREATE:"CUSTOMER_ADDRESS_CREATE",EDIT:"CUSTOMER_ADDRESS_EDIT",DEACTIVATE:"CUSTOMER_ADDRESS_DEACTIVATE"}},supplier:{contacts:{CREATE:"SUPPLIER_CONTACT_CREATE",EDIT:"SUPPLIER_CONTACT_EDIT",DEACTIVATE:"SUPPLIER_CONTACT_DEACTIVATE"},addresses:{CREATE:"SUPPLIER_ADDRESS_CREATE",EDIT:"SUPPLIER_ADDRESS_EDIT",DEACTIVATE:"SUPPLIER_ADDRESS_DEACTIVATE"}}};
function authorize(ctx:RequestContext,parent:ParentKind,child:ChildKind,action:Action){requireModule(ctx,parent==="customer"?"CUSTOMERS":"SUPPLIERS","WRITE");const permission=permissions[parent][child]?.[action];if(!permission)throw new Error("NOT_FOUND");requireTenantPermission(ctx,permission);return ctx.companyId!;}
function audit(ctx:RequestContext,entityType:string,id:string,action:string,before:unknown,after:unknown){return{companyId:ctx.companyId,actorId:ctx.userId,supportAccessId:ctx.supportAccessId,source:"API" as const,module:"MASTER_DATA",entityType,entityId:id,action,beforeData:before==null?undefined:JSON.parse(JSON.stringify(before)) as Prisma.InputJsonValue,afterData:after==null?undefined:JSON.parse(JSON.stringify(after)) as Prisma.InputJsonValue,correlationId:ctx.correlationId};}
async function assertParent(tx:Prisma.TransactionClient,companyId:string,parent:ParentKind,parentId:string){const record=parent==="customer"?await tx.customer.findFirst({where:{id:parentId,companyId}}):await tx.supplier.findFirst({where:{id:parentId,companyId}});if(!record)throw new Error("NOT_FOUND");}
async function assertBranch(tx:Prisma.TransactionClient,companyId:string,customerId:string,branchId?:string|null){if(branchId&&!await tx.customerBranch.findFirst({where:{id:branchId,customerId,companyId}}))throw new Error("NOT_FOUND");}

export async function createChild(ctx:RequestContext,parent:ParentKind,parentId:string,kind:ChildKind,raw:unknown){const companyId=authorize(ctx,parent,kind,"CREATE");return prisma.$transaction(async tx=>{await assertParent(tx,companyId,parent,parentId);let created:Record<string,unknown>&{id:string};if(kind==="contacts"){const value=contactSchema.parse(raw);if(parent==="customer"){await assertBranch(tx,companyId,parentId,value.branchId);if(value.isPrimary)await tx.customerContact.updateMany({where:{companyId,customerId:parentId,active:true},data:{isPrimary:false}});
// Destructure-omit rather than the old `const data:Record<string,unknown>={...value};delete data.canReceiveRfq` —
// widening to Record<string,unknown> made the delete type-check but also erased `firstName`'s
// required-ness, which is what tsc's "Property 'firstName' is missing" error was pointing at.
// This keeps `data`'s real type (so `.create()` below can see firstName is present) while still
// actually removing canReceiveRfq from the object CustomerContact.create receives at runtime
// (CustomerContact has no such column — only SupplierContact does).
const{canReceiveRfq:_canReceiveRfq,...data}=value;created=await tx.customerContact.create({data:{...data,email:value.email||null,companyId,customerId:parentId}});}else{if(value.isPrimary)await tx.supplierContact.updateMany({where:{companyId,supplierId:parentId,active:true},data:{isPrimary:false}});const data={...value};delete data.branchId;created=await tx.supplierContact.create({data:{...data,email:data.email||null,companyId,supplierId:parentId}});}}else if(kind==="addresses"){const value=addressSchema.parse(raw);if(parent==="customer"){await assertBranch(tx,companyId,parentId,value.branchId);if(value.isPrimary)await tx.customerAddress.updateMany({where:{companyId,customerId:parentId,type:value.type,active:true},data:{isPrimary:false}});created=await tx.customerAddress.create({data:{...value,companyId,customerId:parentId}});}else{if(value.isPrimary)await tx.supplierAddress.updateMany({where:{companyId,supplierId:parentId,type:value.type,active:true},data:{isPrimary:false}});const data={...value};delete data.branchId;created=await tx.supplierAddress.create({data:{...data,companyId,supplierId:parentId}});}}else{if(parent!=="customer")throw new Error("NOT_FOUND");const value=branchSchema.parse(raw);created=await tx.customerBranch.create({data:{...value,mainEmail:value.mainEmail||null,companyId,customerId:parentId}});}await tx.auditEvent.create({data:audit(ctx,`${parent}.${kind}`,created.id,"CREATE",null,{parentId,...created})});return created;});}

export async function updateChild(ctx:RequestContext,parent:ParentKind,parentId:string,kind:ChildKind,childId:string,raw:unknown){const companyId=authorize(ctx,parent,kind,"EDIT");return prisma.$transaction(async tx=>{await assertParent(tx,companyId,parent,parentId);let before:Record<string,unknown>|null=null;let updated:Record<string,unknown>&{id:string};if(kind==="contacts"){const value=contactSchema.parse(raw);if(parent==="customer"){before=await tx.customerContact.findFirst({where:{id:childId,customerId:parentId,companyId}});if(!before)throw new Error("NOT_FOUND");await assertBranch(tx,companyId,parentId,value.branchId);if(value.isPrimary)await tx.customerContact.updateMany({where:{companyId,customerId:parentId,active:true,id:{not:childId}},data:{isPrimary:false}});const data:Record<string,unknown>={...value};delete data.canReceiveRfq;updated=await tx.customerContact.update({where:{id:childId},data:{...data,email:value.email||null}});}else{before=await tx.supplierContact.findFirst({where:{id:childId,supplierId:parentId,companyId}});if(!before)throw new Error("NOT_FOUND");if(value.isPrimary)await tx.supplierContact.updateMany({where:{companyId,supplierId:parentId,active:true,id:{not:childId}},data:{isPrimary:false}});const data={...value};delete data.branchId;updated=await tx.supplierContact.update({where:{id:childId},data:{...data,email:data.email||null}});}}else if(kind==="addresses"){const value=addressSchema.parse(raw);if(parent==="customer"){before=await tx.customerAddress.findFirst({where:{id:childId,customerId:parentId,companyId}});if(!before)throw new Error("NOT_FOUND");await assertBranch(tx,companyId,parentId,value.branchId);if(value.isPrimary)await tx.customerAddress.updateMany({where:{companyId,customerId:parentId,type:value.type,active:true,id:{not:childId}},data:{isPrimary:false}});updated=await tx.customerAddress.update({where:{id:childId},data:value});}else{before=await tx.supplierAddress.findFirst({where:{id:childId,supplierId:parentId,companyId}});if(!before)throw new Error("NOT_FOUND");if(value.isPrimary)await tx.supplierAddress.updateMany({where:{companyId,supplierId:parentId,type:value.type,active:true,id:{not:childId}},data:{isPrimary:false}});const data={...value};delete data.branchId;updated=await tx.supplierAddress.update({where:{id:childId},data});}}else{if(parent!=="customer")throw new Error("NOT_FOUND");const value=branchSchema.parse(raw);before=await tx.customerBranch.findFirst({where:{id:childId,customerId:parentId,companyId}});if(!before)throw new Error("NOT_FOUND");updated=await tx.customerBranch.update({where:{id:childId},data:{...value,mainEmail:value.mainEmail||null}});}await tx.auditEvent.create({data:audit(ctx,`${parent}.${kind}`,childId,"UPDATE",before,{parentId,...updated})});return updated;});}

export async function deactivateChild(ctx:RequestContext,parent:ParentKind,parentId:string,kind:ChildKind,childId:string){const companyId=authorize(ctx,parent,kind,"DEACTIVATE");return prisma.$transaction(async tx=>{await assertParent(tx,companyId,parent,parentId);const where={id:childId,companyId,...(parent==="customer"?{customerId:parentId}:{supplierId:parentId})};const delegate=kind==="branches"?tx.customerBranch:parent==="customer"&&kind==="contacts"?tx.customerContact:parent==="customer"?tx.customerAddress:kind==="contacts"?tx.supplierContact:tx.supplierAddress;const before=await(delegate as never as{findFirst(args:unknown):Promise<Record<string,unknown>|null>}).findFirst({where});if(!before)throw new Error("NOT_FOUND");const updated=await(delegate as never as{update(args:unknown):Promise<Record<string,unknown>&{id:string}>}).update({where:{id:childId},data:{active:false,isPrimary:false,deactivatedAt:new Date(),deactivatedById:ctx.userId}});await tx.auditEvent.create({data:audit(ctx,`${parent}.${kind}`,childId,"DEACTIVATE",before,{parentId,...updated})});return updated;});}

export async function setSupplierBrand(ctx:RequestContext,supplierId:string,manufacturerId:string,active:boolean){requireModule(ctx,"SUPPLIERS","WRITE");requireTenantPermission(ctx,"SUPPLIER_BRANDS_MANAGE");const companyId=ctx.companyId!;return prisma.$transaction(async tx=>{await assertParent(tx,companyId,"supplier",supplierId);if(!await tx.manufacturer.findFirst({where:{id:manufacturerId,companyId}}))throw new Error("NOT_FOUND");const key={companyId_supplierId_manufacturerId:{companyId,supplierId,manufacturerId}};const before=await tx.supplierManufacturer.findUnique({where:key});const updated=await tx.supplierManufacturer.upsert({where:key,create:{companyId,supplierId,manufacturerId,active},update:{active,deactivatedAt:active?null:new Date(),deactivatedById:active?null:ctx.userId}});await tx.auditEvent.create({data:audit(ctx,"supplier.brands",updated.id,active?"ACTIVATE":"DEACTIVATE",before,{...updated})});return updated;});}
