import { Prisma } from "@prisma/client";
import { z } from "zod";
import type { RequestContext } from "@/lib/auth/context-types";
import { requireModule, requireTenantPermission } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";
const text=z.string().trim().max(500).optional().nullable();
export const settingsInput=z.object({legalName:z.string().trim().min(2).max(200),tradingName:text,registrationNumber:text,vatNumber:text,mainTelephone:text,mainEmail:z.string().trim().email().optional().nullable().or(z.literal("")),website:text,defaultCurrencyCode:z.string().trim().length(3),defaultTaxJurisdiction:z.string().trim().length(2),defaultTaxCodeId:z.string().cuid().optional().nullable(),defaultPaymentTermId:z.string().cuid().optional().nullable(),quoteValidityDays:z.number().int().min(1).max(365),themeColor:text,logoObjectKey:text,documentHeaderText:text,documentFooterText:z.string().trim().max(2000).optional().nullable()});
function auth(ctx:RequestContext,intent:"READ"|"WRITE"){requireModule(ctx,"DASHBOARD",intent);requireTenantPermission(ctx,intent==="READ"?"COMPANY_SETTINGS_VIEW":"COMPANY_SETTINGS_EDIT");return ctx.companyId!;}
export async function getCompanySettings(ctx:RequestContext){const companyId=auth(ctx,"READ");return prisma.company.findFirstOrThrow({where:{id:companyId},select:{internalCode:true,legalName:true,tradingName:true,settings:true,addresses:true}});}
export async function updateCompanySettings(ctx:RequestContext,raw:unknown){const companyId=auth(ctx,"WRITE");const input=settingsInput.parse(raw);return prisma.$transaction(async tx=>{const before=await tx.company.findUniqueOrThrow({where:{id:companyId},include:{settings:true}});if(input.defaultTaxCodeId&&!await tx.taxCode.findFirst({where:{id:input.defaultTaxCodeId,companyId}}))throw new Error("NOT_FOUND");if(input.defaultPaymentTermId&&!await tx.commercialTerm.findFirst({where:{id:input.defaultPaymentTermId,companyId,type:"PAYMENT"}}))throw new Error("NOT_FOUND");const {legalName,tradingName,...settings}=input;await tx.company.update({where:{id:companyId},data:{legalName,tradingName}});const updated=await tx.companySettings.update({where:{companyId},data:{...settings,mainEmail:settings.mainEmail||null}});await tx.auditEvent.create({data:{companyId,actorId:ctx.userId,supportAccessId:ctx.supportAccessId,source:"API",module:"SETTINGS",entityType:"CompanySettings",entityId:updated.id,action:"UPDATE",beforeData:JSON.parse(JSON.stringify(before)) as Prisma.InputJsonValue,afterData:JSON.parse(JSON.stringify({legalName,tradingName,...updated})) as Prisma.InputJsonValue,correlationId:ctx.correlationId}});return updated;});}
