import type { RequestContext } from "@/lib/auth/context-types";
import { requireModule, requireTenantPermission } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

function readAccess(ctx:RequestContext,parent:"customer"|"supplier"){requireModule(ctx,parent==="customer"?"CUSTOMERS":"SUPPLIERS","READ");requireTenantPermission(ctx,parent==="customer"?"CUSTOMERS_VIEW":"SUPPLIERS_VIEW");return ctx.companyId!;}
export async function getCustomerDetail(ctx:RequestContext,id:string){const companyId=readAccess(ctx,"customer");const record=await prisma.customer.findFirst({where:{id,companyId},include:{branches:{orderBy:[{active:"desc"},{name:"asc"}]},contacts:{include:{branch:{select:{id:true,name:true}}},orderBy:[{active:"desc"},{isPrimary:"desc"},{firstName:"asc"}]},addresses:{include:{branch:{select:{id:true,name:true}}},orderBy:[{active:"desc"},{type:"asc"},{isPrimary:"desc"}]},paymentTerm:true,defaultTaxCode:true}});if(!record)throw new Error("NOT_FOUND");const ids=[id,...record.branches.map(x=>x.id),...record.contacts.map(x=>x.id),...record.addresses.map(x=>x.id)];const history=await prisma.auditEvent.findMany({where:{companyId,entityId:{in:ids},module:"MASTER_DATA"},orderBy:{occurredAt:"desc"},take:100,include:{actor:{select:{displayName:true}}}});return{...record,history};}
export async function getSupplierDetail(ctx:RequestContext,id:string){const companyId=readAccess(ctx,"supplier");const record=await prisma.supplier.findFirst({where:{id,companyId},include:{contacts:{orderBy:[{active:"desc"},{isPrimary:"desc"},{firstName:"asc"}]},addresses:{orderBy:[{active:"desc"},{type:"asc"},{isPrimary:"desc"}]},manufacturers:{include:{manufacturer:true},orderBy:{createdAt:"desc"}},paymentTerm:true}});if(!record)throw new Error("NOT_FOUND");const ids=[id,...record.contacts.map(x=>x.id),...record.addresses.map(x=>x.id),...record.manufacturers.map(x=>x.id)];const history=await prisma.auditEvent.findMany({where:{companyId,entityId:{in:ids},module:"MASTER_DATA"},orderBy:{occurredAt:"desc"},take:100,include:{actor:{select:{displayName:true}}}});return{...record,history};}

export async function customerSelections(ctx:RequestContext,q:string){const companyId=readAccess(ctx,"customer");const contains={contains:q.trim(),mode:"insensitive" as const};return prisma.customer.findMany({where:{companyId,active:true,...(q&&{OR:[{name:contains},{tradingName:contains},{accountCode:contains},{branches:{some:{companyId,active:true,name:contains}}},{contacts:{some:{companyId,active:true,OR:[{firstName:contains},{lastName:contains},{email:contains},{telephone:contains},{mobile:contains}]}}}]})},select:{id:true,name:true,tradingName:true,accountCode:true,branches:{where:{active:true},select:{id:true,name:true,code:true},orderBy:{name:"asc"}},contacts:{where:{active:true},select:{id:true,firstName:true,lastName:true,email:true,branchId:true,isPrimary:true},orderBy:[{isPrimary:"desc"},{firstName:"asc"}]},addresses:{where:{active:true},select:{id:true,type:true,label:true,line1:true,city:true,branchId:true,isPrimary:true},orderBy:[{isPrimary:"desc"},{type:"asc"}]}},orderBy:{name:"asc"},take:20});}
export async function supplierSelections(ctx:RequestContext,q:string){const companyId=readAccess(ctx,"supplier");const contains={contains:q.trim(),mode:"insensitive" as const};return prisma.supplier.findMany({where:{companyId,active:true,...(q&&{OR:[{name:contains},{accountCode:contains},{mainTelephone:contains},{mainEmail:contains},{contacts:{some:{companyId,active:true,OR:[{firstName:contains},{lastName:contains},{email:contains},{telephone:contains}]}}}]})},select:{id:true,name:true,accountCode:true,contacts:{where:{active:true},select:{id:true,firstName:true,lastName:true,email:true,isPrimary:true},orderBy:[{isPrimary:"desc"},{firstName:"asc"}]}},orderBy:{name:"asc"},take:20});}
