import{afterAll,beforeAll,describe,expect,it}from"vitest";import{ModuleKey,PrismaClient}from"@prisma/client";import type{RequestContext}from"@/lib/auth/context-types";import{DEFAULT_TENANT_PERMISSIONS}from"@/lib/auth/permissions";import{AuthorizationError}from"@/lib/auth/guards";import{createChild,updateChild,deactivateChild,setSupplierBrand}from"@/lib/master-data/child-service";import{getCustomerDetail,getSupplierDetail,customerSelections,supplierSelections}from"@/lib/master-data/detail-service";import{createMaster}from"@/lib/master-data/service";
const url=process.env.DATABASE_URL_TEST;if(!url)throw new Error("DATABASE_URL_TEST is required");const db=new PrismaClient({datasources:{db:{url}}});const suffix=`p21_${Date.now()}_${Math.random().toString(36).slice(2)}`;let a="",b="",ua="",ub="";
function ctx(companyId:string,userId:string,permissions=DEFAULT_TENANT_PERMISSIONS.COMPANY_ADMIN,overrides:Partial<RequestContext>={}):RequestContext{return{userId,displayName:"P21 test",companyId,companyInternalCode:suffix,tenantRole:"COMPANY_ADMIN",tenantPermissions:new Set(permissions),platformPermissions:new Set(),supportAccessId:null,supportMode:null,moduleAccess:new Map(Object.values(ModuleKey).map(k=>[k,"FULL" as const])),correlationId:suffix,...overrides}}
async function customer(c:RequestContext,name:string){return createMaster(c,"customers",{name})}async function supplier(c:RequestContext,name:string){return createMaster(c,"suppliers",{name})}async function manufacturer(c:RequestContext,name:string){return createMaster(c,"manufacturers",{name})}
beforeAll(async()=>{const[ca,cb]=await Promise.all([db.company.create({data:{internalCode:`A_${suffix}`,legalName:"Tenant A",settings:{create:{}}}}),db.company.create({data:{internalCode:`B_${suffix}`,legalName:"Tenant B",settings:{create:{}}}})]);a=ca.id;b=cb.id;const[x,y]=await Promise.all([db.userIdentity.create({data:{email:`a-${suffix}@test.local`,displayName:"A",passwordHash:"x"}}),db.userIdentity.create({data:{email:`b-${suffix}@test.local`,displayName:"B",passwordHash:"x"}})]);ua=x.id;ub=y.id});
afterAll(async()=>{for(const companyId of[a,b]){await db.auditEvent.deleteMany({where:{companyId}});await db.supplierManufacturer.deleteMany({where:{companyId}});await db.customerContact.deleteMany({where:{companyId}});await db.customerAddress.deleteMany({where:{companyId}});await db.customerBranch.deleteMany({where:{companyId}});await db.supplierContact.deleteMany({where:{companyId}});await db.supplierAddress.deleteMany({where:{companyId}});await db.part.deleteMany({where:{companyId}});await db.serviceItem.deleteMany({where:{companyId}});await db.customer.deleteMany({where:{companyId}});await db.supplier.deleteMany({where:{companyId}});await db.storageLocation.deleteMany({where:{companyId}});await db.manufacturer.deleteMany({where:{companyId}});await db.companySettings.deleteMany({where:{companyId}});await db.documentNumberSequence.deleteMany({where:{companyId}});await db.taxCode.deleteMany({where:{companyId}});await db.commercialTerm.deleteMany({where:{companyId}})}await db.company.deleteMany({where:{id:{in:[a,b]}}});await db.userIdentity.deleteMany({where:{id:{in:[ua,ub]}}});await db.$disconnect()});
describe("Phase 2.1 child master-data",()=>{
  it("creates branch, branch-linked contact and typed address and audits them",async()=>{const c=await customer(ctx(a,ua),"Contact Customer");const branch=await createChild(ctx(a,ua),"customer",c.id,"branches",{name:"HQ"});const contact=await createChild(ctx(a,ua),"customer",c.id,"contacts",{firstName:"Primary",email:"p@x.test",isPrimary:true,branchId:branch.id});expect(contact.companyId).toBe(a);expect(contact.branchId).toBe(branch.id);const addr=await createChild(ctx(a,ua),"customer",c.id,"addresses",{type:"POSTAL",line1:"Box 1",isPrimary:true});expect(addr.type).toBe("POSTAL");for(const[id,action]of[[branch.id,"CREATE"],[contact.id,"CREATE"],[addr.id,"CREATE"]]as const){expect(await db.auditEvent.count({where:{companyId:a,entityId:id,action}})).toBeGreaterThan(0)}});
  it("updates a child and preserves tenant scoping",async()=>{const c=await customer(ctx(a,ua),"Edit Customer");const contact=await createChild(ctx(a,ua),"customer",c.id,"contacts",{firstName:"Old"});const updated=await updateChild(ctx(a,ua),"customer",c.id,"contacts",contact.id,{firstName:"New",position:"Manager"});expect(updated.firstName).toBe("New");expect(updated.id).toBe(contact.id)});
  it("deactivates a child and records actor and timestamp",async()=>{const c=await customer(ctx(a,ua),"Deact Customer");const contact=await createChild(ctx(a,ua),"customer",c.id,"contacts",{firstName:"Gone",isPrimary:true});const deactivated=await deactivateChild(ctx(a,ua),"customer",c.id,"contacts",contact.id);expect(deactivated.active).toBe(false);expect(deactivated.isPrimary).toBe(false);expect(deactivated.deactivatedById).toBe(ua);expect(deactivated.deactivatedAt).toBeInstanceOf(Date);expect(await db.auditEvent.count({where:{companyId:a,entityId:contact.id,action:"DEACTIVATE"}})).toBe(1)});
  it("rejects cross-tenant child IDs for update and deactivate without leaking existence",async()=>{const ca=await customer(ctx(a,ua),"Owner");const cb=await customer(ctx(b,ub),"Other");const foreign=await createChild(ctx(b,ub),"customer",cb.id,"contacts",{firstName:"Foreign"});await expect(updateChild(ctx(a,ua),"customer",ca.id,"contacts",foreign.id,{firstName:"Intrude"})).rejects.toThrow("NOT_FOUND");await expect(deactivateChild(ctx(a,ua),"customer",ca.id,"contacts",foreign.id)).rejects.toThrow("NOT_FOUND");await expect(getCustomerDetail(ctx(a,ua),cb.id)).rejects.toThrow("NOT_FOUND");await expect(getSupplierDetail(ctx(a,ua),(await supplier(ctx(b,ub),"Foreign Sup")).id)).rejects.toThrow("NOT_FOUND")});
  it("rejects cross-tenant branch links on create and update",async()=>{const ca=await customer(ctx(a,ua),"Branch Owner A");const cb=await customer(ctx(b,ub),"Branch Owner B");const badBranch=await createChild(ctx(b,ub),"customer",cb.id,"branches",{name:"Foreign Branch"});await expect(createChild(ctx(a,ua),"customer",ca.id,"contacts",{firstName:"X",branchId:badBranch.id})).rejects.toThrow("NOT_FOUND");const goodContact=await createChild(ctx(a,ua),"customer",ca.id,"contacts",{firstName:"X"});await expect(updateChild(ctx(a,ua),"customer",ca.id,"contacts",goodContact.id,{firstName:"X",branchId:badBranch.id})).rejects.toThrow("NOT_FOUND")});

  it("enforces branch ownership within a tenant (branch from another customer is rejected)",async()=>{const ca1=await customer(ctx(a,ua),"Parent One");const ca2=await customer(ctx(a,ua),"Parent Two");const otherBranch=await createChild(ctx(a,ua),"customer",ca2.id,"branches",{name:"Other Branch"});await expect(createChild(ctx(a,ua),"customer",ca1.id,"contacts",{firstName:"X",branchId:otherBranch.id})).rejects.toThrow("NOT_FOUND")});
  it("switches primary contact transactionally so only one active primary exists",async()=>{const c=await customer(ctx(a,ua),"Primary Contact");const one=await createChild(ctx(a,ua),"customer",c.id,"contacts",{firstName:"One",isPrimary:true});const two=await createChild(ctx(a,ua),"customer",c.id,"contacts",{firstName:"Two",isPrimary:true});expect(two.isPrimary).toBe(true);const reloaded=await db.customerContact.findUniqueOrThrow({where:{id:one.id}});expect(reloaded.isPrimary).toBe(false);expect(await db.customerContact.count({where:{companyId:a,customerId:c.id,active:true,isPrimary:true}})).toBe(1)});
  it("switches primary address per type while keeping other types independent",async()=>{const c=await customer(ctx(a,ua),"Primary Address");const bill1=await createChild(ctx(a,ua),"customer",c.id,"addresses",{type:"BILLING",line1:"A1",isPrimary:true});const bill2=await createChild(ctx(a,ua),"customer",c.id,"addresses",{type:"BILLING",line1:"A2",isPrimary:true});const del=await createChild(ctx(a,ua),"customer",c.id,"addresses",{type:"DELIVERY",line1:"D1",isPrimary:true});expect(bill2.isPrimary).toBe(true);expect((await db.customerAddress.findUniqueOrThrow({where:{id:bill1.id}})).isPrimary).toBe(false);expect(del.isPrimary).toBe(true);expect(await db.customerAddress.count({where:{companyId:a,customerId:c.id,type:"BILLING",active:true,isPrimary:true}})).toBe(1);expect(await db.customerAddress.count({where:{companyId:a,customerId:c.id,type:"DELIVERY",active:true,isPrimary:true}})).toBe(1)});
  it("isolates supplier/manufacturer brand relationships to the tenant",async()=>{const s=await supplier(ctx(a,ua),"Brand Supplier");const m=await manufacturer(ctx(a,ua),"Brand A");const mB=await manufacturer(ctx(b,ub),"Brand B");const sB=await supplier(ctx(b,ub),"Other Sup");const link=await setSupplierBrand(ctx(a,ua),s.id,m.id,true);expect(link.active).toBe(true);await expect(setSupplierBrand(ctx(a,ua),s.id,mB.id,true)).rejects.toThrow("NOT_FOUND");await expect(setSupplierBrand(ctx(b,ub),sB.id,m.id,true)).rejects.toThrow("NOT_FOUND");await expect(setSupplierBrand(ctx(b,ub),s.id,mB.id,true)).rejects.toThrow("NOT_FOUND")});
  it("scopes detail reads and selections to the tenant",async()=>{const ca=await customer(ctx(a,ua),"Selection Alpha");const cb=await customer(ctx(b,ub),"Selection Secret");const detail=await getCustomerDetail(ctx(a,ua),ca.id);expect(detail.id).toBe(ca.id);expect((await customerSelections(ctx(a,ua),"Selection Secret")).some(x=>x.id===cb.id)).toBe(false);expect((await customerSelections(ctx(a,ua),"Selection Alpha")).some(x=>x.id===ca.id)).toBe(true);const sa=await supplier(ctx(a,ua),"Sup Alpha");expect((await supplierSelections(ctx(a,ua),"Sup Alpha")).some(x=>x.id===sa.id)).toBe(true);expect((await supplierSelections(ctx(b,ub),"Sup Alpha")).length).toBe(0)});
  it("enforces permissions, module entitlements, read-only licensing and read-only support",async()=>{const c=await customer(ctx(a,ua),"Authz Customer");const noContact=new Set(DEFAULT_TENANT_PERMISSIONS.COMPANY_ADMIN);noContact.delete("CUSTOMER_CONTACT_CREATE");await expect(createChild(ctx(a,ua,noContact),"customer",c.id,"contacts",{firstName:"X"})).rejects.toThrow(AuthorizationError);const grace={...ctx(a,ua),moduleAccess:new Map(ctx(a,ua).moduleAccess).set("CUSTOMERS","READ_ONLY" as const)};await expect(createChild(grace,"customer",c.id,"contacts",{firstName:"X"})).rejects.toThrow(AuthorizationError);const support={...ctx(a,ua),supportAccessId:"support",supportMode:"READ_ONLY" as const};await expect(createChild(support,"customer",c.id,"contacts",{firstName:"X"})).rejects.toThrow(AuthorizationError);const noBrand=new Set(DEFAULT_TENANT_PERMISSIONS.COMPANY_ADMIN);noBrand.delete("SUPPLIER_BRANDS_MANAGE");const s=await supplier(ctx(a,ua),"Brand Authz Sup");const m=await manufacturer(ctx(a,ua),"Brand Authz Mfr");await expect(setSupplierBrand(ctx(a,ua,noBrand),s.id,m.id,true)).rejects.toThrow(AuthorizationError)});
});

