"use client";

/* eslint-disable react-hooks/set-state-in-effect -- async platform module loading intentionally mirrors existing workspace patterns */
import { useEffect, useState } from "react";
import { Plus } from "lucide-react";

type ModuleEntry = { id: string; code: string; name: string; category: string; status: string; version: string; route?: string | null };

export default function PlatformModulesPage() {
  const [items, setItems] = useState<ModuleEntry[]>([]);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ code: "", moduleKey: "", name: "", description: "", category: "Workshop", status: "ACTIVE", version: "1.0.0", route: "", assignableToTenants: true, userAssignable: true, dependsOn: [] as string[] });
  async function load() { const r = await fetch("/api/v1/platform/modules", { cache: "no-store" }); const b = await r.json(); if (!r.ok) throw new Error(b.error?.message || "Unable to load modules."); setItems(b); }
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "Unable to load modules.")); }, []);
  async function createModule() { setSaving(true); setError(""); try { const r = await fetch("/api/v1/platform/modules", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, moduleKey: form.moduleKey || null }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error?.message || "Unable to create module."); setForm({ code: "", moduleKey: "", name: "", description: "", category: "Workshop", status: "ACTIVE", version: "1.0.0", route: "", assignableToTenants: true, userAssignable: true, dependsOn: [] }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create module."); } finally { setSaving(false); } }
  return <div><header className="page-header compact"><div><p className="eyebrow">Platform</p><h1>Modules</h1><p>Register and manage module metadata, categories, dependencies and tenant assignment capability.</p></div></header>{error ? <div className="inline-error">{error}</div> : null}<section className="detail-panel"><header><div><h2>Register module</h2></div><div className="header-actions"><button type="button" className="gold-button" disabled={saving || form.code.trim().length < 2 || form.name.trim().length < 2} onClick={() => void createModule()}><Plus size={14} /> Create</button></div></header><div className="drawer-fields"><label><span>Internal code</span><input value={form.code} onChange={(e) => setForm((c) => ({ ...c, code: e.target.value.toUpperCase() }))} /></label><label><span>Mapped ModuleKey (optional)</span><input value={form.moduleKey} onChange={(e) => setForm((c) => ({ ...c, moduleKey: e.target.value.toUpperCase() }))} /></label><label><span>Name</span><input value={form.name} onChange={(e) => setForm((c) => ({ ...c, name: e.target.value }))} /></label><label><span>Category</span><input value={form.category} onChange={(e) => setForm((c) => ({ ...c, category: e.target.value }))} /></label><label><span>Status</span><select value={form.status} onChange={(e) => setForm((c) => ({ ...c, status: e.target.value }))}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="PLANNED">Planned</option></select></label><label><span>Version</span><input value={form.version} onChange={(e) => setForm((c) => ({ ...c, version: e.target.value }))} /></label><label><span>Route</span><input value={form.route} onChange={(e) => setForm((c) => ({ ...c, route: e.target.value }))} /></label><label className="wide"><span>Description</span><textarea rows={3} value={form.description} onChange={(e) => setForm((c) => ({ ...c, description: e.target.value }))} /></label></div></section><section className="detail-panel"><header><div><h2>Module catalog</h2></div></header><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Module</th><th>Category</th><th>Status</th><th>Version</th><th>Route</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong>{item.code ? <div className="muted small-line">{item.code}</div> : null}</td><td>{item.category}</td><td>{item.status}</td><td>{item.version}</td><td>{item.route || ""}</td></tr>)}{items.length === 0 && <tr><td colSpan={5} className="table-state compact-empty-state">No modules found.</td></tr>}</tbody></table></div></section></div>;
}
