"use client";
/* eslint-disable jsx-a11y/role-supports-aria-props -- native aside is the visual drawer container */
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ChevronLeft, ChevronRight, Loader2, Plus, Search, X } from "lucide-react";

type Field={key:string;label:string;type?:"text"|"email"|"number"|"date"|"select"|"textarea"|"checkbox";required?:boolean;options?:Array<{value:string;label:string}>;placeholder?:string};
type Column={key:string;label:string;render?:(row:Record<string,unknown>)=>string};
export type MasterConfig={kind:string;title:string;eyebrow:string;description:string;singular:string;fields:Field[];columns:Column[]};
type ListResponse={items:Array<Record<string,unknown>&{id:string;active?:boolean}>;total:number;page:number;pageSize:number};
function valueAt(row:Record<string,unknown>,path:string){return path.split(".").reduce<unknown>((v,k)=>v&&typeof v==="object"?(v as Record<string,unknown>)[k]:undefined,row);}
export function MasterDataWorkspace({ config, detailHref }: { config: MasterConfig; detailHref?: (row: Record<string, unknown> & { id: string }) => string }) {
  const [data,setData]=useState<ListResponse>({items:[],total:0,page:1,pageSize:25}); const [q,setQ]=useState(""); const [status,setStatus]=useState("active"); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<(Record<string,unknown>&{id:string})|null>(null); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams({q,status,page:String(page),pageSize:"25"});const r=await fetch(`/api/v1/master-data/${config.kind}?${p}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error?.message||"Unable to load records.");setData(body);}catch(e){setError(e instanceof Error?e.message:"Unable to load records.");}finally{setLoading(false);}},[config.kind,page,q,status]);
  useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t);},[load]);
  const pages=Math.max(1,Math.ceil(data.total/data.pageSize));
  function show(row?:Record<string,unknown>&{id:string}){setEditing(row||null);setOpen(true);}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const fd=new FormData(e.currentTarget);const payload:Record<string,unknown>={};for(const f of config.fields){const raw=fd.get(f.key);if(f.type==="checkbox")payload[f.key]=raw==="on";else if(f.type==="number")payload[f.key]=raw===""?null:Number(raw);else payload[f.key]=raw===""?null:raw;}try{const r=await fetch(`/api/v1/master-data/${config.kind}${editing?`/${editing.id}`:""}`,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.error?.message||"Unable to save.");setOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setSaving(false);}}
  return <><header className="page-header master-header"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.description}</p></div><button className="gold-button" onClick={()=>show()}><Plus size={15}/> New {config.singular}</button></header>
    <section className="master-panel"><div className="master-toolbar"><label className="search-control"><Search size={15}/><input aria-label={`Search ${config.title}`} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder={`Search ${config.title.toLowerCase()}…`}/></label><select aria-label="Status filter" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All statuses</option></select><span>{data.total} record{data.total===1?"":"s"}</span></div>
      {error&&<div className="inline-error">{error}</div>}{loading?<div className="table-state"><Loader2 className="spin" size={20}/>Loading…</div>:data.items.length===0?<div className="table-state">No matching records. Create the first {config.singular.toLowerCase()} when ready.</div>:<div className="data-table-wrap"><table className="data-table"><thead><tr>{config.columns.map(c=><th key={c.key}>{c.label}</th>)}<th>Status</th><th></th></tr></thead><tbody>{data.items.map(row=><tr key={row.id}>{config.columns.map(c=><td key={c.key}>{c.render?c.render(row):String(valueAt(row,c.key)??"—")}</td>)}<td><span className={`status-pill ${row.active===false?"neutral":""}`}>{row.active===false?"Inactive":"Active"}</span></td><td>{detailHref?<Link className="table-action" href={detailHref(row)}>View</Link>:null}<button className="table-action" onClick={()=>show(row)}>Edit</button></td></tr>)}</tbody></table></div>}
      <footer className="table-footer"><span>Page {data.page} of {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={14}/></button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={14}/></button></div></footer></section>
    {open&&<div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="form-drawer" aria-modal="true"><header><div><p className="eyebrow">Master data</p><h2>{editing?"Edit":"New"} {config.singular}</h2></div><button aria-label="Close" onClick={()=>setOpen(false)}><X size={18}/></button></header><form onSubmit={submit}><div className="drawer-fields">{config.fields.map(f=><label key={f.key} className={f.type==="textarea"?"wide":""}>{f.type==="checkbox"?<><input name={f.key} type="checkbox" defaultChecked={editing?Boolean(editing[f.key]):f.key==="active"}/><span>{f.label}</span></>:<><span>{f.label}{f.required&&" *"}</span>{f.type==="select"?<select name={f.key} required={f.required} defaultValue={String(editing?.[f.key]??"")}><option value="">Select…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==="textarea"?<textarea name={f.key} defaultValue={String(editing?.[f.key]??"")} rows={4}/>:<input name={f.key} type={f.type||"text"} required={f.required} step={f.type==="number"?"0.0001":undefined} defaultValue={String(editing?.[f.key]??"")} placeholder={f.placeholder}/>}</>}</label>)}</div><footer><button type="button" className="quiet-button" onClick={()=>setOpen(false)}>Cancel</button><button className="gold-button" disabled={saving}>{saving?<Loader2 className="spin" size={15}/>:null}{saving?"Saving…":"Save"}</button></footer></form></aside></div>}</>;
}
