"use client";
/* eslint-disable react-hooks/set-state-in-effect -- async loaders synchronize this view with REST resources */
import Link from "next/link";import{useCallback,useEffect,useState}from"react";import{ArrowLeft,Building2,Loader2,Mail,MapPin,Plus,Star,UserRound,X}from"lucide-react";
type Row=Record<string,unknown>&{id:string;active?:boolean;isPrimary?:boolean};type Party=Row&{name:string;branches?:Row[];contacts:Row[];addresses:Row[];manufacturers?:Array<Row&{manufacturer:Row}>;history:Array<Row&{actor?:{displayName:string}|null}>};type Tab="overview"|"branches"|"contacts"|"addresses"|"brands"|"commercial"|"history";
const labels:Record<string,string>={firstName:"First name",lastName:"Surname",position:"Position / title",telephone:"Telephone",mobile:"Mobile",email:"Email",notes:"Notes",name:"Branch / site name",code:"Code / reference",mainTelephone:"Main telephone",mainEmail:"Main email",type:"Address type",label:"Address label",line1:"Address line 1",line2:"Address line 2",city:"City",province:"Province",postalCode:"Postal code",countryCode:"Country",branchId:"Branch / site",isPrimary:"Primary / default",active:"Active"};
const fields:Record<string,string[]>={branches:["name","code","mainTelephone","mainEmail","notes","active"],contacts:["firstName","lastName","position","telephone","mobile","email","branchId","notes","isPrimary","active"],addresses:["type","label","line1","line2","city","province","postalCode","countryCode","branchId","isPrimary","active"]};
function text(v:unknown){return v==null||v===""?"—":String(v)}
export function PartyDetailWorkspace({kind,id}:{kind:"customers"|"suppliers";id:string}){const singular=kind==="customers"?"customer":"supplier";const[party,setParty]=useState<Party|null>(null);const[tab,setTab]=useState<Tab>("overview");const[editing,setEditing]=useState<{child:string;row:Row|null}|null>(null);const[error,setError]=useState("");const[saving,setSaving]=useState(false);const[manufacturers,setManufacturers]=useState<Row[]>([]);
const load=useCallback(async()=>{try{const r=await fetch(`/api/v1/${kind}/${id}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error?.message);setParty(b)}catch(e){setError(e instanceof Error?e.message:"Unable to load details.")}},[id,kind]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(kind==="suppliers"&&tab==="brands")fetch("/api/v1/master-data/manufacturers?status=active&pageSize=100").then(r=>r.json()).then(b=>setManufacturers(b.items||[]));},[kind,tab]);
async function saveChild(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setSaving(true);setError("");const form=new FormData(e.currentTarget);const payload:Record<string,unknown>={};for(const key of fields[editing.child]){const raw=form.get(key);payload[key]=["isPrimary","active"].includes(key)?raw==="on":raw===""?null:raw}try{const base=`/api/v1/${kind}/${id}/${editing.child}`;const r=await fetch(editing.row?`${base}/${editing.row.id}`:base,{method:editing.row?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error?.message);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save.")}finally{setSaving(false)}}
async function deactivate(child:string,row:Row){if(!confirm(`Deactivate this ${child.slice(0,-1)}?`))return;const r=await fetch(`/api/v1/${kind}/${id}/${child}/${row.id}`,{method:"DELETE"});if(!r.ok){const b=await r.json();setError(b.error?.message||"Unable to deactivate.");return}await load()}
async function brand(manufacturerId:string,active:boolean){const r=await fetch(`/api/v1/suppliers/${id}/brands/${manufacturerId}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({active})});if(!r.ok){const b=await r.json();setError(b.error?.message||"Unable to update brand.");return}await load()}
if(!party)return <div className="table-state">{error||<><Loader2 className="spin" size={18}/>Loading details…</>}</div>;const tabs:Array<[Tab,string]>=[["overview","Overview"],...(kind==="customers"?[["branches","Branches"] as [Tab,string]]:[]),["contacts","Contacts"],["addresses","Addresses"],...(kind==="suppliers"?[["brands","Brands"] as [Tab,string]]:[]),["commercial","Commercial"],["history","Activity"]];const rows=tab==="branches"?party.branches||[]:tab==="contacts"?party.contacts:tab==="addresses"?party.addresses:[];
return <><header className="detail-head"><div><Link href={`/${kind}`}><ArrowLeft size={15}/> Back to {kind}</Link><p className="eyebrow">{singular} master</p><h1>{party.name}</h1><span>{text(party.accountCode)} · {party.active?"Active":"Inactive"}</span></div><Link className="gold-button" href={`/${kind}`}>Edit account from list</Link></header><nav className="detail-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>{error&&<div className="inline-error">{error}</div>}
{tab==="overview"&&<div className="detail-grid"><Info title="Account identity" icon={<Building2/>} values={[["Legal / account name",party.name],["Trading name",party.tradingName],["Registration",party.registrationNumber],["VAT number",party.vatNumber]]}/><Info title="Primary communication" icon={<Mail/>} values={[["Telephone",party.mainTelephone],["Email",party.mainEmail],["Website",party.website]]}/><Info title="Record coverage" icon={<UserRound/>} values={[["Branches",party.branches?.length||0],["Contacts",party.contacts.length],["Addresses",party.addresses.length]]}/></div>}
{["branches","contacts","addresses"].includes(tab)&&<section className="detail-panel"><header><div><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2><p>Active and historical {tab} linked to this {singular}.</p></div><button className="gold-button" onClick={()=>setEditing({child:tab,row:null})}><Plus size={14}/> Add</button></header><div className="record-list">{rows.length===0?<div className="table-state">No {tab} recorded.</div>:rows.map(row=><article key={row.id} className={!row.active?"inactive":""}><div className="record-icon">{tab==="addresses"?<MapPin/>:tab==="branches"?<Building2/>:<UserRound/>}</div><div><strong>{tab==="branches"?text(row.name):tab==="contacts"?`${text(row.firstName)} ${row.lastName||""}`:text(row.label||row.type)}</strong><span>{tab==="contacts"?text(row.email||row.mobile||row.telephone):tab==="addresses"?`${text(row.line1)}, ${text(row.city)}`:text(row.code||row.mainEmail)}</span></div>{row.isPrimary&&<span className="primary-badge"><Star size={11}/> Primary</span>}<span className={`status-pill ${!row.active?"neutral":""}`}>{row.active?"Active":"Inactive"}</span><button className="table-action" onClick={()=>setEditing({child:tab,row})}>Edit</button>{row.active&&<button className="table-action danger" onClick={()=>deactivate(tab,row)}>Deactivate</button>}</article>)}</div></section>}
{tab==="brands"&&<section className="detail-panel"><header><div><h2>Manufacturers & brands</h2><p>Shared manufacturer relationships used by procurement and RFQs.</p></div></header><div className="brand-grid">{manufacturers.map(m=>{const linked=party.manufacturers?.find(x=>(x.manufacturer as Row).id===m.id);return <article key={m.id}><div><strong>{text(m.name)}</strong><span>{text(m.code)}</span></div><button className={linked?.active?"quiet-button":"gold-button"} onClick={()=>brand(m.id,!linked?.active)}>{linked?.active?"Remove":"Add brand"}</button></article>})}</div></section>}
{tab==="commercial"&&<div className="detail-grid"><Info title="Commercial defaults" icon={<Building2/>} values={[["Currency",party.currencyCode],["Payment terms",(party.paymentTerm as Row|undefined)?.label],["Default tax",(party.defaultTaxCode as Row|undefined)?.code],["Credit limit",party.creditLimit],["Account on hold",party.accountOnHold?"Yes":"No"]]}/><Info title="Commercial notes" icon={<Mail/>} values={[["Notes",party.notes]]}/></div>}
{tab==="history"&&<section className="detail-panel"><header><div><h2>Activity history</h2><p>Central audit events for this account and its child records.</p></div></header><div className="history-list">{party.history.map(h=><article key={h.id}><strong>{text(h.action).replaceAll("_"," ")}</strong><span>{text(h.entityType)} · {h.actor?.displayName||"System"}</span><time>{new Date(String(h.occurredAt)).toLocaleString("en-ZA")}</time></article>)}</div></section>}
{editing&&<div className="drawer-backdrop"><aside className="form-drawer" role="dialog" aria-modal="true"><header><div><p className="eyebrow">{singular} detail</p><h2>{editing.row?"Edit":"Add"} {editing.child.slice(0,-1)}</h2></div><button onClick={()=>setEditing(null)}><X size={18}/></button></header><form onSubmit={saveChild}><div className="drawer-fields">{fields[editing.child].map(key=><label key={key} className={key==="notes"?"wide":""}>{["isPrimary","active"].includes(key)?<><input name={key} type="checkbox" defaultChecked={editing.row?Boolean(editing.row[key]):key==="active"}/><span>{labels[key]}</span></>:<><span>{labels[key]}</span>{key==="notes"?<textarea name={key} rows={4} defaultValue={text(editing.row?.[key])==="—"?"":text(editing.row?.[key])}/>:key==="type"?<select name={key} defaultValue={text(editing.row?.[key])==="—"?"":text(editing.row?.[key])}>{["BILLING","DELIVERY","PHYSICAL","POSTAL"].map(x=><option key={x}>{x}</option>)}</select>:key==="branchId"?<select name={key} defaultValue={text(editing.row?.[key])==="—"?"":text(editing.row?.[key])}><option value="">Account level</option>{party.branches?.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{text(x.name)}</option>)}</select>:<input name={key} type={key.toLowerCase().includes("email")?"email":"text"} required={["firstName","name","line1"].includes(key)} defaultValue={text(editing.row?.[key])==="—"?"":text(editing.row?.[key])}/>}</>}</label>)}</div><footer><button type="button" className="quiet-button" onClick={()=>setEditing(null)}>Cancel</button><button className="gold-button" disabled={saving}>{saving&&<Loader2 className="spin" size={14}/>} Save</button></footer></form></aside></div>}</>}
function Info({title,icon,values}:{title:string;icon:React.ReactNode;values:Array<[string,unknown]>}){return <section className="info-card"><header>{icon}<h2>{title}</h2></header><dl>{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{text(value)}</dd></div>)}</dl></section>}
